name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Archive artifacts (Geyser Fabric)
        # See https://github.com/actions/upload-artifact/commits
      uses: actions/upload-artifact@main
      if: success()
      with:
        name: Geyser Fabric
        path: bootstrap/fabric/build/libs/Geyser-Fabric.jar
        if-no-files-found: error
    - name: Archive artifacts (Geyser Standalone)
      uses: actions/upload-artifact@main
      if: success()
      with:
        name: Geyser Standalone
        path: bootstrap/standalone/build/libs/Geyser-Standalone.jar
        if-no-files-found: error
    - name: Archive artifacts (Geyser Spigot)
      uses: actions/upload-artifact@main
      if: success()
      with:
        name: Geyser Spigot
        path: bootstrap/spigot/build/libs/Geyser-Spigot.jar
        if-no-files-found: error
    - name: Archive artifacts (Geyser BungeeCord)
      uses: actions/upload-artifact@main
      if: success()
      with:
        name: Geyser BungeeCord
        path: bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar
        if-no-files-found: error
    - name: Archive artifacts (Geyser Velocity)
      uses: actions/upload-artifact@main
      if: success()
      with:
        name: Geyser Velocity
        path: bootstrap/velocity/build/libs/Geyser-Velocity.jar
        if-no-files-found: error
